### PR TITLE
Handle Web IDL

### PR DESCRIPTION
**Pull request by annevk**
See https://github.com/heycam/webidl/pull/1018 for context.

Disclaimer: I haven't actually gotten `npm run pp-webidl -- --input index.html` to run locally yet.

### CODE REVIEW

**Comment by domenic** [comment]
I think the best setup would be to not run `npm install` as part of deploy.sh or the makefile, but instead have the CI build do the installation using `@actions/setup-node`.

So, that'd require some additional work in `.github/workflows`, I guess :-/.

**Comment by andreubotella** [comment]
WebIDL's makefile was running `webidl-pp` for non-deploy builds, and its `.pr-preview.json` file had `"post-processing": {"name": "webidl-grammar"}`. The post-build steps will instead only run as part of `make deploy`. Now, the `webidl-pp` transformation isn't necessary on local or preview builds, since it will happen dynamically on page load anyway, but let's make sure that this isn't a difference that gets overlooked.

Also, there's the `check-grammar.js` script that makes sure the WebIDL grammar stays as LL(1). That should probably also run as part of the post-build steps.

**Comment by annevk** [comment]
I'm happy with this now.

I've not tackled `.pr-preview.json`. I did notice it, but I think at some point we probably want `.pr-preview.json` to use the output of the build process and not the output of Bikeshed/Wattsi. And as you note it is okay either way.

**Comment by annevk** [comment]
I'm not sure why I added the "do not merge yet" label, but I think this can be merged. I've also run it for https://github.com/heycam/webidl/pull/1018 and included the output therein.

I could change the node-version back to 16 if desired. I noticed we use 14 elsewhere which is why I went with that here. Up to @domenic.

Note that this PR now also adds the ability to run `factory.py` without generating PRs and with the ability to create changes for a single repository, which is useful for things that are being transitioned.

**Review by domenic — APPROVED** [review]

**Pull request merged**
