### PR TITLE
Handle the streams repo (previously skipped)

### PR DESCRIPTION
**Pull request by foolip**

### CODE REVIEW

**Comment by foolip** [comment]
Aha, so that's the trick. Wasn't sure how to handle the difference yet.

**Comment by foolip** [comment]
> I imagine running this on whatwg/streams should produce no changes from the current master, right?

https://github.com/whatwg/spec-factory/pull/14 was just merged, so it does, but here's the single change not related to that:
```diff
diff --git a/Makefile b/Makefile
index 60a5dd7..1179275 100644
--- a/Makefile
+++ b/Makefile
@@ -7,7 +7,7 @@ remote: index.bs
                               --write-out "%{http_code}" \
                               --header "Accept: text/plain, text/html" \
                               -F die-on=warning \
-                                                                                                -F md-Text-Macro="COMMIT-SHA LOCAL COPY" \
+                              -F md-Text-Macro="COMMIT-SHA LOCAL COPY" \
                               -F file=@index.bs) && \
        [[ "$$HTTP_STATUS" -eq "200" ]]) || ( \
                echo ""; cat index.html; echo ""; \
```

(A whitespace indentation change.)

**Comment by domenic** [comment]
Ah, great, my bad for messing that up I guess.

But if #14 was merged, then we need more work here, right? Since build.yml needs more steps for streams, namely npm install, npm test, and submodules.

**Comment by foolip** [comment]
I would recommend just putting the tests in a separate workflow, and not tracking that with spec-factory. The only thing you can't do then is have the deploy on master depend on the tests passing on master, but do you want that?

**Comment by domenic** [comment]
> I would recommend just putting the tests in a separate workflow, and not tracking that with spec-factory.

This would mean, a separate file? That seems nice, to keep things separated into "standard WHATWG stuff" and "Streams specific stuff".

However, that does imply that we didn't need Node.js in any of the existing workflows after all. Maybe we should remove that.

> The only thing you can't do then is have the deploy on master depend on the tests passing on master, but do you want that?

We do not want to merge any PRs into master which make the tests fail. But I guess that could be done via branch protection?

**Comment by foolip** [comment]
> This would mean, a separate file? That seems nice, to keep things separated into "standard WHATWG stuff" and "Streams specific stuff".

> We do not want to merge any PRs into master which make the tests fail. But I guess that could be done via branch protection?

Yes, both of these are what I had in mind.

> However, that does imply that we didn't need Node.js in any of the existing workflows after all. Maybe we should remove that.

Ah, nice! I'll make it so.

**Pull request merged**
