### PR TITLE
Add GitHub Actions build.yml template

### PR DESCRIPTION
**Pull request by foolip**
Also remove any files that are part of the Travis setup.

Part of https://github.com/whatwg/meta/issues/173.

### CODE REVIEW

**Comment by domenic** [comment]
This probably needs exceptions for streams and encoding at least, to not generate a deploy.yml for them since they are special.

**Comment by foolip** [comment]
It looks like encodings is different only in that it requires Python 3.8, but https://github.com/actions/virtual-environments/blob/master/images/linux/Ubuntu2004-README.md already has 3.8. It's not as locked down as picking a version we want using `actions/setup-python@v2`, but is likely to work fine in practice. The same with anything needing node, actually, since some version is available by default.

**Comment by foolip** [comment]
For streams there's already an exception to not process it at all in `factory.py`, so that one's OK.

**Comment by andreubotella** [comment]
> For streams there's already an exception to not process it at all in `factory.py`, so that one's OK.

That shouldn't stay there for much longer, since #1035 is now merged.

**Comment by foolip** [comment]
I've tweaked this a bit and it seems to work when run:
https://github.com/whatwg/encoding/pull/218
https://github.com/whatwg/fullscreen/pull/175

Sort of, one can tell from the directory names that something's wrong.

**Comment by foolip** [comment]
Blush. After the first two worked I eagerly commented before the second two had finished on the assumption they would run. I'll investigate why the did not.

**Comment by foolip** [comment]
Explaining the appearance of Travis being stuck on multiple PRs, as in https://github.com/whatwg/compat/pull/126#issuecomment-643360783.

For most repos the Travis status is required by branch protection. That makes the status appear to be pending even though it won't be triggered. For each repo I handle, I'll update the branch protection as I land the change.

**Pull request merged**
