### PR TITLE
Use the new LS-PR status for PR previews

### PR DESCRIPTION
**Pull request by domenic**
Follows https://github.com/tabatkins/bikeshed/pull/1635.

### CODE REVIEW

**Comment by annevk** [comment]
- [ ] https://github.com/whatwg/compat/pull/124
- [ ] https://github.com/whatwg/console/pull/170
- [ ] https://github.com/whatwg/dom/pull/853
- [ ] https://github.com/whatwg/encoding/pull/205
- [ ] https://github.com/whatwg/fetch/pull/1017
- [ ] https://github.com/whatwg/fullscreen/pull/168
- [ ] https://github.com/whatwg/infra/pull/297
- [ ] https://github.com/whatwg/mimesniff/pull/120
- [ ] https://github.com/whatwg/notifications/pull/156
- [ ] https://github.com/whatwg/quirks/pull/50
- [ ] https://github.com/whatwg/storage/pull/81
- [ ] https://github.com/whatwg/streams/pull/1034 (reusing existing PR that wasn't merged yet)
- [ ] https://github.com/whatwg/url/pull/474
- [ ] https://github.com/whatwg/xhr/pull/273

**Comment by annevk** [comment]
I have merged what I can and assigned the remainder.

**Comment by domenic** [comment]
Did we want to actually merge this PR to spec-factory? :)

**Comment by annevk** [comment]
Fair enough. I thought we could use it as tracking issue, but that doesn't make a whole lot of sense at this point as the switch has been made.

**Pull request merged**
